HisabPro.Web/Controllers/Private/ImportController.cs
using HisabPro.Common;
using HisabPro.Constants;
using HisabPro.Constants.Resources;
using HisabPro.DTO.Model;
using HisabPro.DTO.Request;
using HisabPro.DTO.Response;
using HisabPro.Services.Implements;
using HisabPro.Services.Interfaces;
using HisabPro.Web.Helper;
using HisabPro.DTO.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using System.Net;
using System.Text.Json;

namespace HisabPro.Web.Controllers.Private
{
    [Authorize]
    public class ImportController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ICategoryService _categoryService;
        private readonly IExpenseService _expenseService;
        private readonly IIncomeService _incomeService;
        private readonly ISharedViewLocalizer _localizer;

        public ImportController(IAccountService accountService, ICategoryService categoryService, IExpenseService expenseService, IIncomeService incomeService, ISharedViewLocalizer localizer)
        {
            _accountService = accountService;
            _categoryService = categoryService;
            _expenseService = expenseService;
            _incomeService = incomeService;
            _localizer = localizer;
        }

        public async Task<ActionResult> Expense()
        {
            await setCatgoriesInJson(EnumCategoryType.Expense);
            return View();
        }

        public async Task<ActionResult> Income()
        {
            await setCatgoriesInJson(EnumCategoryType.Income);
            return View();
        }

        public IActionResult Upload()
        {
            return PartialView("_Upload");
        }

        public async Task<IActionResult> SaveFile(IFormFile file)
        {
            var response = new ResponseDTO<object>();
            response.StatusCode = HttpStatusCode.BadRequest;

            if (file != null && file.Length > 0)
            {
                // Validate file extension
                var extension = Path.GetExtension(file.FileName).ToLower();
                if (extension != ".xls" && extension != ".xlsx")
                {
                    response.Message = _localizer.Get(ResourceKey.LabelApiImportFileAllowedExtensions);
                }

                // Extract original file name and extension
                var originalFileName = Path.GetFileNameWithoutExtension(file.FileName);
                var fileExtension = Path.GetExtension(file.FileName);
                // Generate a unique name with a timestamp
                var timestamp = DateTime.Now.ToString("yyyyMMddHHmmss");
                var newFileName = $"{originalFileName}-{timestamp}{fileExtension}";

                try
                {
                    // Define the path to save the uploaded file
                    var path = Path.Combine(Directory.GetCurrentDirectory(), AppConst.Configs.UploadFolderPath, newFileName);

                    // Save the file to the specified path
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                catch (Exception)
                {

                    throw;
                }

                response.StatusCode = HttpStatusCode.OK;
                response.Message = _localizer.Get(ResourceKey.LabelApiImportSuccess);
                response.Response = new { FileName = newFileName };
            }
            else
            {
                response.Message = _localizer.Get(ResourceKey.LabelApiImportFileRequired);
            }

            return StatusCode((int)response.StatusCode, response);
        }

        [HttpGet]
        public async Task<IActionResult> Extraction(string filename)
        {
            var excelService = new ExcelService();
            var folder = AppConst.Configs.UploadFolderPath;
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), folder, filename);

            var rawData = excelService.ReadExcelFile(filePath);

            var listExpense = rawData.Select(data => new ImportDataModel
            {
                Date = getDateTime(data[0]),
                Description = data[1],
                Amount = int.TryParse(data[2], out int amount) ? amount : 0,
                Category = data[3],
                SubCategory = data[4],
                Person = data[5]
            }).ToList();

            var accounts = await _accountService.GetAccountsAsync();
            accounts.Insert(0, new IdNameRes { Id = string.Empty, Name = string.Empty });
            ViewData["Accounts"] = new SelectList(accounts, "Id", "Name");

            var url = HttpContext.Request.Headers["Referer"].ToString();
            //var url = HttpContext.Request.Path.Value;
            string categoryType = StringHelper.GetActionFromUrl(url);
            var categories = await _categoryService.GetCategoriesAsync(categoryType.ToUpper() == "INCOME" ? EnumCategoryType.Income : EnumCategoryType.Expense);
            categories.Insert(0, new IdNameRes { Id = string.Empty, Name = string.Empty });
            ViewData["Categories"] = new SelectList(categories, "Id", "Name");

            return PartialView("_Extraction", listExpense);
        }

        [HttpPost]
        public async Task<IActionResult> SaveExpenses([FromBody] List<SaveExpenseReq> expenses)
        {
            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();

            var response = await _expenseService.AddRangeAsync(expenses);
            stopwatch.Stop();

            response.Response.TotalTimeTaken = stopwatch.Elapsed.Seconds;
            return StatusCode((int)response.StatusCode, response);
        }
        [HttpPost]
        public async Task<IActionResult> SaveIncomes([FromBody] List<SaveIncomeReq> incomes)
        {
            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();

            var response = await _incomeService.AddRangeAsync(incomes);
            stopwatch.Stop();

            response.Response.TotalTimeTaken = stopwatch.Elapsed.Seconds;
            return StatusCode((int)response.StatusCode, response);
        }

        public IActionResult Summary(int totalRecords, int totalSeconds)
        {
            return PartialView("_Summary", new SummaryModel() { Records = totalRecords, Seconds = totalSeconds });
        }

        private async Task setCatgoriesInJson(EnumCategoryType categoryType)
        {
            var categories = await _categoryService.GetCategoriesAsync(categoryType);
            ViewData["Categories"] = JsonSerializer.Serialize(categories);
            var childCategories = await _categoryService.GetSubCategoriesAsync(categoryType);
            ViewData["SubCategories"] = JsonSerializer.Serialize(childCategories);
        }
        private DateTime? getDateTime(string rawDate)
        {
            // Assign value
            if (string.IsNullOrWhiteSpace(rawDate))
            {
                return null; // Set null if the input is empty
            }
            else
            {
                // Try parsing the date and assign it
                if (DateTime.TryParse(rawDate, out DateTime parsedDate))
                {
                    return parsedDate.Date; // Set only the date part (time is discarded)
                }
                else
                {
                    return null;
                }
            }
        }
    }
}

HisabPro.Web/Controllers/Private/IncomesController.cs
using AutoMapper;
using HisabPro.Constants;
using HisabPro.Constants.Resources;
using HisabPro.DTO.Model;
using HisabPro.DTO.Request;
using HisabPro.DTO.Response;
using HisabPro.Services.Implements;
using HisabPro.Services.Interfaces;
using HisabPro.Web.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ColType = HisabPro.DTO.Model.Type;

namespace HisabPro.Web.Controllers.Private
{
    [Authorize]
    public class IncomesController : Controller
    {
        private readonly IIncomeService _incomeService;
        private readonly IAccountService _accountService;
        private readonly IMapper _mapper;
        private readonly ISharedViewLocalizer _localizer;
        private readonly IExportDataService _exportDataService;

        public IncomesController(IIncomeService incomeService, IAccountService accountService,
            IMapper mapper, ISharedViewLocalizer localizer, IExportDataService exportDataService)
        {
            _incomeService = incomeService;
            _accountService = accountService;
            _mapper = mapper;
            _localizer = localizer;
            _exportDataService = exportDataService;
        }

        public async Task<IActionResult> Index()
        {
            var accounts = await _accountService.GetAccountsAsync();
            var fields = new List<BaseFilterModel>
            {
                new FilterModel<string> {
                    FieldName = "Title",
                    FieldTitle= _localizer.Get(ResourceKey.FieldTitle),
                },
                new FilterModel<int> {
                    FieldName = "AccountId",
                    FieldTitle= _localizer.Get(ResourceKey.FieldAccount),
                    Items =  _mapper.Map<List<IdNameAndRefId>>(accounts),
                },
                new FilterModel<DateTime> {
                    FieldName = "IncomeOn",
                    FieldTitle= _localizer.Get(ResourceKey.LabelFilterDateRange)
                },
                new FilterModel<string> {
                    FieldName = "Note",
                    FieldTitle= _localizer.Get(ResourceKey.FieldNote),
                },
                new FilterModel<bool> {
                    FieldName = "IsActive",
                    FieldTitle= _localizer.Get(ResourceKey.FieldIsActive)
                },
                new FilterModel<bool> {
                    FieldName = "IsBulkImported",
                    FieldTitle= _localizer.Get(ResourceKey.LabelFilterBulkImported)
                }
            };

            var filter = new FilterViewModel
            {
                Fields = fields,
            };
            var req = new LoadDataRequest() { Filter = filter };
            var model = await LoadGridData(req, true);
            return View(model);
        }
        public async Task<IActionResult> Load([FromBody] LoadDataRequest req)
        {
            var model = await LoadGridData(req);
            return PartialView("~/Views/Shared/_GridViewBody.cshtml", model);
        }

        public async Task<IActionResult> Save(int? id)
        {
            var accounts = await _accountService.GetAccountsAsync();
            accounts.Insert(0, new IdNameRes { Id = string.Empty, Name = string.Empty });
            ViewData["AccountId"] = new SelectList(accounts, "Id", "Name");

            if (id != null)
            {
                var model = await _incomeService.GetByIdAsync(id.Value);
                return View(model);

            }
            return View(new SaveIncomeReq { IsActive = true, IncomeOn = DateTime.Now });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save([Bind("Id,Title,IncomeOn,Amount,Note,AccountId,IsActive")] SaveIncomeReq req)
        {
            var response = await _incomeService.SaveAsync(req);
            return StatusCode((int)response.StatusCode, response);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromBody] DeleteReq req)
        {
            var response = await _incomeService.DeleteAsync(req.Id);
            return StatusCode((int)response.StatusCode, response); ;
        }

        [HttpPost]
        public async Task<IActionResult> Export([FromBody] ExportReq req)
        {
            var allPageData = await ExportDataHelper.GetData(req, _incomeService.ExportData);
            var data = allPageData.Data;
            return _exportDataService.Export(data, EnumReportTitle.Income, req, getGridColumns());
        }

        /// <summary>
        /// This is used for generic gridview component which will perform sorting and pagination
        /// </summary>
        /// <param name="req"></param>
        /// <returns></returns>
        private async Task<GridViewModel<object>> LoadGridData(LoadDataRequest req, bool firstTimeLoad = false)
        {
            return await GridviewHelper.LoadGridData(req, firstTimeLoad, _incomeService.PageData, getGridColumns());
        }

        private List<Column> getGridColumns()
        {
            return new List<Column> {
                    new Column() { Name = "Title", Title = _localizer.Get(ResourceKey.FieldTitle), Width = "170px"  },
                    new Column() { Name = "IncomeOn", Title = _localizer.Get(ResourceKey.FieldDate), Type = ColType.Date, Width = "100px" },
                    new Column() { Name = "Amount", Title = _localizer.Get(ResourceKey.FieldAmount), Align = Align.Right, Width="95px" },
                    new Column() { Name = "Category", Title = _localizer.Get(ResourceKey.FieldCategory), Width = "140px" },
                    new Column() { Name = "SubCategory", Title = _localizer.Get(ResourceKey.FieldSubCategory), Width = "150px" },
                    new Column() { Name = "Account", Title = _localizer.Get(ResourceKey.FieldAccount), Width = "150px" },
                    new Column() { Name = "IsBulkImported", Title= _localizer.Get(ResourceKey.LabelColumnImport), Width = "90px", Type = ColType.Checkbox },
                    new Column() { Name = "Note", Title = _localizer.Get(ResourceKey.FieldNote), IsSortable = false},
                    new Column() { Name = "Edit", Type = ColType.Edit },
                    new Column() { Name = "Delete", Type = ColType.Delete }
            };
        }
    }
}

HisabPro.Web/Controllers/Private/TaxController.cs
using HisabPro.Constants;
using HisabPro.Constants.Resources;
using HisabPro.DTO.Model;
using HisabPro.DTO.Response;
using HisabPro.Services.Interfaces;
using HisabPro.Web.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HisabPro.Web.Controllers.Private
{
    [Authorize]
    public class TaxController : Controller
    {
        private readonly ITaxService _taxService;
        private readonly ISharedViewLocalizer _localizer;
        private readonly ICategoryService _categoryService;

        public TaxController(ITaxService taxService, ISharedViewLocalizer sharedViewLocalizer, ICategoryService categoryService)
        {
            _taxService = taxService;
            _localizer = sharedViewLocalizer;
            _categoryService = categoryService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new TaxInputModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult IncomeTax(TaxInputModel input)
        {
            var result = new TaxResultModel
            {
                AnnualIncome = input.AnnualIncome
            };

            result.TaxAmount = _taxService.CalculateNewRegimeTax(result.TaxableIncome, result);

            if (result.TaxAmount == 0)
            {
                result.ResultMessage = $"🎉 {_localizer.Get(ResourceKey.NoTaxApplicable)}";
            }
            else
            {
                result.ResultMessage = string.Format(_localizer.Get(ResourceKey.TaxApplicable), result.TaxAmount);
            }

            return View("IncomeTaxResult", result);
        }

        [HttpGet]
        public IActionResult Zakat()
        {
            return View(new List<ZakatIncomeItem>());
        }
        public async Task<IActionResult> IncomesForZakat()
        {
            var categories = await _categoryService.GetCategoriesAsync(EnumCategoryType.Income);
            categories.Insert(0, new IdNameRes { Id = string.Empty, Name = string.Empty });
            categories.Insert(categories.Count(), new IdNameRes { Id = ZakatIncomeItem.IncomeTypeForOtherId.ToString(), Name = ZakatIncomeItem.IncomeTypeForOtherName });
            ViewData["Categories"] = new SelectList(categories, "Id", "Name");

            var errorMessage = string.Format(_localizer[ResourceKey.ValidationRequired], _localizer[ResourceKey.Description]);
            ViewData["errorMsgDescription"] = errorMessage;
            return PartialView("_IncomesForZakat", new ZakatIncomeItem());
        }

        [HttpPost]
        public IActionResult SaveZakat([FromBody] List<ZakatIncomeItem> Items)
        {
            return View();
        }


            [HttpGet]
        public IActionResult Khums()
        {
            return View();
        }
    }
}

HisabPro.Web/Views/Shared/AccessDenied.cshtml
@inject HisabPro.Constants.ISharedViewLocalizer _localizer
@using HisabPro.Constants.Resources;
@{
    ViewData["Title"] = _localizer.Get(ResourceKey.LabelAccessDenied);
}

<h1 class="text-danger">@_localizer.Get(ResourceKey.LabelAccessDenied)</h1>
<p class="text-danger">@_localizer.Get(ResourceKey.LabelAccessDeniedMessage)</p>
<p>
    <a asp-area="" asp-controller="Home" asp-action="Index">@_localizer.Get(ResourceKey.LabelGoToHome)</a>
</p>

HisabPro.Web/Views/Shared/Unauthorized.cshtml
@inject HisabPro.Constants.ISharedViewLocalizer _localizer
@using HisabPro.Constants.Resources;
@model ErrorDTO
@{
    ViewData["Title"] = _localizer.Get(ResourceKey.LabelUnauthorized);
}

<h1 class="text-danger">@_localizer.Get(ResourceKey.LabelUnauthorized)</h1>
<p class="text-danger">@_localizer.Get(ResourceKey.LabelUnauthorizedMessage)</p>
<p>
    <a asp-area="" asp-controller="Home" asp-action="Index">@_localizer.Get(ResourceKey.LabelGoToHome)</a>
</p>

HisabPro.Web/Views/Shared/_ConfirmPartial.cshtml
@inject HisabPro.Constants.ISharedViewLocalizer _localizer
@using HisabPro.Constants.Resources;
<div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="confirmModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalLabel">@_localizer.Get(ResourceKey.LabelConfirmTitle)</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div id="confirmModalText" class="modal-body">
                @_localizer.Get(ResourceKey.LabelConfirmMessage)
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@_localizer.Get(ResourceKey.LabelCancel)</button>
                <button type="button" class="btn btn-primary" id="confirmButton">@_localizer.Get(ResourceKey.LabelConfirm)</button>
            </div>
        </div>
    </div>
</div>

HisabPro.Web/Views/Shared/_EditLayout.cshtml
@inject HisabPro.Constants.ISharedViewLocalizer _localizer
@using HisabPro.Constants.Resources;
@{ 
    Layout = "~/Views/Shared/_PrivateLayout.cshtml";
}

<div class="card mb-1" style="position:relative">
    <div class="card-header d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
            <i class="bi bi-save me-2"></i>
            <h5 class="mb-0 p-2">@ViewData["CardTitle"]</h5>
        </div>
        <div>
            <a asp-action="Index" class="btn btn-light btn-back border">
                <i class="bi bi-arrow-left me-2"></i> @_localizer.Get(ResourceKey.LabelBackToList)
            </a>
        </div>
    </div>
    <div class="grid-filter-body card-body">
        <div class="row">
            <div class="col-md-12">
                @RenderSection("BodyContent", required: true)
            </div>
        </div>
    </div>
    <div id="form-view" class="loading" style="display:none">
        @_localizer.Get(ResourceKey.LabelLoading)
    </div>
</div>

@RenderSection("Scripts", required: false)

HisabPro.Web/Views/Shared/_PrivateLayout.cshtml
@inject HisabPro.Constants.ISharedViewLocalizer _localizer
@using HisabPro.Constants.Resources;
@{
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}

<style type="text/css">

    body {
        font-family: Verdana;
        font-size: 14px;
        padding-top: 60px; /* Ensure content is pushed below the navbar */
    }

    #brandLogo {
        cursor: pointer;
        margin: 0px 20px 0px 0px;
    }

        #brandLogo img {
            height: 38px;
            vertical-align: middle;
        }


    .sidebar {
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        background-color: #e7e9ea;
        border-right: 1px solid #dee2e6;
        padding: 1rem;
        width: 250px;
        padding-right: 1px;
    }

        .sidebar a {
            color: #212529;
            text-decoration: none;
            display: block;
            margin: 0.5rem 0;
            padding: 0.5rem;
            border-radius: 5px;
        }

            .sidebar a:hover {
                background-color: #e9ecef;
                color: #495057;
            }
    /* Highlight active submenu */
    .sidebar-menu a.active {
        background: #c4e0d4;
        font-weight: bold;
    }

    .main-content {
        margin-left: 250px; /* for sidebar */
        padding: 1.5rem;
        width: 100%;
    }

    .navbar {
        position: fixed;
        width: calc(100% - 250px);
        margin-left: 250px;
        z-index: 1030;
        top: 0px;
    }

</style>

<!-- Sidebar -->
<div class="d-flex">
    <!-- Sidebar -->
    <div class="sidebar d-flex flex-column">
        <div class="sidebar-header">
            <h4 id="brandLogo" class="text-center"><img src="~/icons/Logo-Transaparent.png" alt="HisabPro Logo"> HisabPro</h4>
        </div>
        <div class="sidebar-menu flex-grow-1 overflow-auto">
            <a asp-controller="Dashboard" asp-action="Index" class="active"><i class="bi bi-house-fill"></i> @_localizer.Get(ResourceKey.LabelDashboard)</a>

            <!-- Collapsible Menu for Admin -->
            <a class="d-flex justify-content-between align-items-center" data-menu="adminSubmenu" role="button">
                <span><i class="bi bi-person-gear"></i> @_localizer.Get(ResourceKey.LabelRoleAdmin)</span>
                <i class="menu-arrow bi bi-caret-down-fill"></i>
            </a>
            <div class="collapse" id="adminSubmenu">
                <a asp-controller="Accounts" asp-action="Index" class="ms-3"><i class="bi bi-wallet2"></i> @_localizer.Get(ResourceKey.LabelAccounts)</a>
                <a asp-controller="Category" asp-action="Index" class="ms-3"><i class="bi bi-tags"></i> @_localizer.Get(ResourceKey.LabelCategories)</a>
                <a asp-controller="Expenses" asp-action="Index" class="ms-3"><i class="bi bi-cash-stack"></i> @_localizer.Get(ResourceKey.LabelExpenses)</a>
                <a asp-controller="Incomes" asp-action="Index" class="ms-3"><i class="bi bi-graph-up-arrow"></i> @_localizer.Get(ResourceKey.LabelIncomes)</a>
                <a asp-controller="User" asp-action="Index" class="ms-3"><i class="bi bi-people"></i> @_localizer.Get(ResourceKey.LabelUsers)</a>
            </div>

            <!-- Collapsible Menu for Import -->
            <a class="d-flex justify-content-between align-items-center" data-menu="importSubmenu" role="button">
                <span><i class="bi bi-file-arrow-up"></i> @_localizer.Get(ResourceKey.LabelImports)</span>
                <i class="menu-arrow bi bi-caret-down-fill"></i>
            </a>
            <div class="collapse" id="importSubmenu">
                <a asp-controller="Import" asp-action="Expense" class="ms-3"><i class="bi bi-cash-stack"></i> @_localizer.Get(ResourceKey.LabelExpenses)</a>
                <a asp-controller="Import" asp-action="Income" class="ms-3"><i class="bi bi-cash-coin"></i> @_localizer.Get(ResourceKey.LabelIncomes)</a>
            </div>

            <!-- Collapsible Menu for Reports -->
            <a class="d-flex justify-content-between align-items-center" data-menu="reportsSubmenu" role="button">
                <span><i class="bi bi-file-earmark-bar-graph"></i> @_localizer.Get(ResourceKey.LabelReports)</span>
                <i class="menu-arrow bi bi-caret-down-fill"></i>
            </a>
            <div class="collapse" id="reportsSubmenu">
                <a asp-controller="Reports" asp-action="Index" class="ms-3"><i class="bi bi-clipboard-data"></i> @_localizer.Get(ResourceKey.LabelReportIncomeExpense)</a>
                <a href="#" class="ms-3"><i class="bi bi-pie-chart"></i> @_localizer.Get(ResourceKey.LabelAnnualReports)</a>
            </div>

            <!-- Collapsible Menu for Analytics -->
           @*  <a class="d-flex justify-content-between align-items-center" data-menu="analyticsSubmenu" role="button">
                <span><i class="bi bi-graph-up"></i> @_localizer.Get(ResourceKey.LabelAnalytics)</span>
                <i class="menu-arrow bi bi-caret-down-fill"></i>
            </a>
            <div class="collapse" id="analyticsSubmenu">
                <a href="#" class="ms-3"><i class="bi bi-bar-chart"></i> @_localizer.Get(ResourceKey.LabelTrendAnalysis)</a>
                <a href="#" class="ms-3"><i class="bi bi-activity"></i> @_localizer.Get(ResourceKey.LabelActivityReports)</a>
            </div> *@

            <!-- Collapsible Menu for Analytics -->
            <a class="d-flex justify-content-between align-items-center" data-menu="taxCalculatorSubmenu" role="button">
                <span><i class="bi bi-calculator"></i> @_localizer.Get(ResourceKey.LabelTaxCalculator)</span>
                <i class="menu-arrow bi bi-caret-down-fill"></i>
            </a>
            <div class="collapse" id="taxCalculatorSubmenu">
                <a asp-controller="Tax" asp-action="Index" class="ms-3"><i class="bi bi-globe2"></i> @_localizer.Get(ResourceKey.LabelIncomeTax)</a>
                <a asp-controller="Tax" asp-action="Zakat" class="ms-3"><i class="bi bi-moon"></i> @_localizer.Get(ResourceKey.LabelZakat)</a>
                <a asp-controller="Tax" asp-action="Khums" class="ms-3"><i class="bi bi-star"></i> @_localizer.Get(ResourceKey.LabelKhums)</a>
            </div>

            <a href="#"><i class="bi bi-gear-fill"></i> @_localizer.Get(ResourceKey.LabelSettings)</a>
        </div>
    </div>

    <!-- Main Content -->
    <div class="main-content">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>

</div>

<!-- Render the Scripts section -->
@section Scripts {
    @RenderSection("Scripts", required: false)
    <script>
        $(document).ready(function () {
            $("#publicBrand, #publicMenu").hide();

            $("#brandLogo").click(function () {
                window.location.href = '/Home/Index';
            });

            // Adjust on page load and window resize
            adjustSidebarHeight();
            $(window).resize(adjustSidebarHeight);

            // Restore sidebar state from localStorage
            restoreLeftMenuState();

            // Handle click event for toggling menus
            toggleLeftMenu();

            // Highlight active link
            highlightActiveMenu();
        });

        function adjustSidebarHeight() {
            const sideHeaderHeight = $('.sidebar-header').height();
            const footerHeight = $('.footer').height();
            const windowHeight = $(window).height();
            const sidebarHeight = windowHeight - (sideHeaderHeight + footerHeight) + 10;
            //console.log('sh:' + sideHeaderHeight + ', fh: ' + footerHeight + ', wh: ' + windowHeight + ', sh: ', sidebarHeight);

            $('.sidebar').height(sidebarHeight);
        }

        function restoreLeftMenuState() {
            $(".collapse").each(function () {
                var menuId = $(this).attr("id");
                const isExpanded = JSON.parse(localStorage.getItem("sidebar_" + menuId));
                var menuArrow = $("[data-menu='" + menuId + "']").find(".menu-arrow");

                if (isExpanded === true) {
                    $(this).addClass("show"); // Keep it open
                }
                setMenuArrowIcon(menuArrow, isExpanded);
            });
        }

        function toggleLeftMenu() {
            $("[data-menu]").click(function () {
                var menuId = $(this).attr("data-menu");
                var targetMenu = $("#" + menuId);
                var menuArrow = $(this).find(".menu-arrow");

                targetMenu.collapse("toggle");

                // Store state in localStorage
                var isExpanded = menuArrow.hasClass("bi-caret-down-fill");
                localStorage.setItem("sidebar_" + menuId, JSON.stringify(isExpanded));

                setMenuArrowIcon(menuArrow, isExpanded);
            });
        }

        function highlightActiveMenu() {
            var currentUrl = window.location.pathname.toLowerCase();
            $(".sidebar-menu a").each(function () {
                $(this).removeClass("active");
                var linkHref = $(this).attr("href");
                if (linkHref && currentUrl === linkHref.toLowerCase()) {
                    $(this).addClass("active");
                }
            });
        }

        function setMenuArrowIcon(menuArrow, isExpanded) {
            if (!isExpanded) {
                menuArrow.removeClass("bi-caret-up-fill").addClass("bi-caret-down-fill");
            }
            else {
                menuArrow.removeClass("bi-caret-down-fill").addClass("bi-caret-up-fill");
            }
        }
    </script>
}